### ISSUE TITLE
What is `Node.__position__`

### ISSUE THREAD

**Issue by ReblochonMasque** [andreacortis/wild_six#1]
Hey there Andrea of the wild_six,

I forked your repo and going through the code I could not figure what `Node.__position__` was intended for.

Thanks.

**Comment by andreacortis** [comment]
Hi, I was thinking of having an arbitrary set of Node labels (not necessarily just '1', '2', '3', '4', '5', '6'), for instance in the tests I have

`N = Nodes(nodes='1b3456')`

where the Node with label `'b'` has `__position__ == 1`. 
This allows me to define the order for arbitrary labels like `'1' < 'b'` and  `'b' < 3` (I figure that it could come handy later)

Does it make sense?

**Comment by ReblochonMasque** [comment]
Noted, thank you. Maybe, IDK if it makes sense?  
I also noticed your test throwing a string with an invalid node at your `class Nodes`... I also don't know if it makes sense; maybe?

In spite of his claims to the contrary, Pr. Wildberger's definitions are not as tight as he thought! ;)

**Comment by andreacortis** [comment]
I am probably over-engineering the whole thing :) Not sure which test are you referring to exactly ... could you please copy-paste here? Thanks

**Comment by ReblochonMasque** [comment]
Line 3 of your test file: `N = Nodes(nodes='1b3456')`

**Comment by andreacortis** [comment]
That is actually not an exception, in this OO implementation of the Wildeberger language, you can call `'1', '2' etc` anything you like, because those are just the `labels`. For instance, these are valid instantiations of the Nodes class:

```
In [1]: Nodes('123456')
Out[1]: Nodes(6) = 1,2,3,4,5,6

In [2]: Nodes('abcdefgh')
Out[2]: Nodes(8) = a,b,c,d,e,f,g,h

In [3]: Nodes('♠♥♦♣')
Out[3]: Nodes(4) = ♠,♥,♦,♣
```

Was that what you were referring to?
